name: 'grace-tf-module-member-account'
description: 'Terraform module for AWS subaccounts that is used in GRACE. This module is a supporting module that is required for [grace-core](https://github.com/GSA/grace-core) but may be used independently by other projects if required.'
license: null
openSourceProject: 1
governmentWideReuseProject: 1
tags:
    - open-source
    - opensource
    - gsa-it
    - devsecops
    - grace
contact:
    email: devsecops-core@gsa.gov
