version: 2
jobs:
  validate:
    docker:
      - image: hashicorp/terraform
    steps:
      - checkout
      - run:
          name: Set up Terraform
          command: cd terraform/modules/member_account && terraform init -backend=false

      - run:
          name: Validate Terraform
          command: cd terraform/modules/member_account && terraform validate -check-variables=false

workflows:
    version: 2

    validate:
      jobs:
        - validate
